flyway.url=jdbc:postgresql://db:5432/routematch
flyway.user=postgres
flyway.password=postgres
flyway.locations=filesystem:/flyway/sql
flyway.connectRetries=10
flyway.validateMigrationNaming=true
flyway.baselineOnMigrate=true
