# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import driver_state_service_pb2 as driver__state__service__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in driver_state_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DriverStateServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCandidates = channel.unary_unary(
                '/routematch.shared.proto.v1.DriverStateService/GetCandidates',
                request_serializer=driver__state__service__pb2.GetCandidatesRequest.SerializeToString,
                response_deserializer=driver__state__service__pb2.GetCandidatesResponse.FromString,
                _registered_method=True)
        self.UpdateLocation = channel.unary_unary(
                '/routematch.shared.proto.v1.DriverStateService/UpdateLocation',
                request_serializer=driver__state__service__pb2.UpdateLocationRequest.SerializeToString,
                response_deserializer=driver__state__service__pb2.UpdateLocationResponse.FromString,
                _registered_method=True)
        self.BatchGetCandidates = channel.unary_unary(
                '/routematch.shared.proto.v1.DriverStateService/BatchGetCandidates',
                request_serializer=driver__state__service__pb2.BatchGetCandidatesRequest.SerializeToString,
                response_deserializer=driver__state__service__pb2.BatchGetCandidatesResponse.FromString,
                _registered_method=True)


class DriverStateServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GetCandidates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateLocation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchGetCandidates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DriverStateServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCandidates': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCandidates,
                    request_deserializer=driver__state__service__pb2.GetCandidatesRequest.FromString,
                    response_serializer=driver__state__service__pb2.GetCandidatesResponse.SerializeToString,
            ),
            'UpdateLocation': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateLocation,
                    request_deserializer=driver__state__service__pb2.UpdateLocationRequest.FromString,
                    response_serializer=driver__state__service__pb2.UpdateLocationResponse.SerializeToString,
            ),
            'BatchGetCandidates': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchGetCandidates,
                    request_deserializer=driver__state__service__pb2.BatchGetCandidatesRequest.FromString,
                    response_serializer=driver__state__service__pb2.BatchGetCandidatesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'routematch.shared.proto.v1.DriverStateService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('routematch.shared.proto.v1.DriverStateService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DriverStateService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetCandidates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/routematch.shared.proto.v1.DriverStateService/GetCandidates',
            driver__state__service__pb2.GetCandidatesRequest.SerializeToString,
            driver__state__service__pb2.GetCandidatesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateLocation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/routematch.shared.proto.v1.DriverStateService/UpdateLocation',
            driver__state__service__pb2.UpdateLocationRequest.SerializeToString,
            driver__state__service__pb2.UpdateLocationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchGetCandidates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/routematch.shared.proto.v1.DriverStateService/BatchGetCandidates',
            driver__state__service__pb2.BatchGetCandidatesRequest.SerializeToString,
            driver__state__service__pb2.BatchGetCandidatesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
