// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: driver_state_service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	DriverStateService_GetCandidates_FullMethodName      = "/routematch.shared.proto.v1.DriverStateService/GetCandidates"
	DriverStateService_UpdateLocation_FullMethodName     = "/routematch.shared.proto.v1.DriverStateService/UpdateLocation"
	DriverStateService_BatchGetCandidates_FullMethodName = "/routematch.shared.proto.v1.DriverStateService/BatchGetCandidates"
)

// DriverStateServiceClient is the client API for DriverStateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DriverStateServiceClient interface {
	GetCandidates(ctx context.Context, in *GetCandidatesRequest, opts ...grpc.CallOption) (*GetCandidatesResponse, error)
	UpdateLocation(ctx context.Context, in *UpdateLocationRequest, opts ...grpc.CallOption) (*UpdateLocationResponse, error)
	BatchGetCandidates(ctx context.Context, in *BatchGetCandidatesRequest, opts ...grpc.CallOption) (*BatchGetCandidatesResponse, error)
}

type driverStateServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDriverStateServiceClient(cc grpc.ClientConnInterface) DriverStateServiceClient {
	return &driverStateServiceClient{cc}
}

func (c *driverStateServiceClient) GetCandidates(ctx context.Context, in *GetCandidatesRequest, opts ...grpc.CallOption) (*GetCandidatesResponse, error) {
	out := new(GetCandidatesResponse)
	err := c.cc.Invoke(ctx, DriverStateService_GetCandidates_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverStateServiceClient) UpdateLocation(ctx context.Context, in *UpdateLocationRequest, opts ...grpc.CallOption) (*UpdateLocationResponse, error) {
	out := new(UpdateLocationResponse)
	err := c.cc.Invoke(ctx, DriverStateService_UpdateLocation_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverStateServiceClient) BatchGetCandidates(ctx context.Context, in *BatchGetCandidatesRequest, opts ...grpc.CallOption) (*BatchGetCandidatesResponse, error) {
	out := new(BatchGetCandidatesResponse)
	err := c.cc.Invoke(ctx, DriverStateService_BatchGetCandidates_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DriverStateServiceServer is the server API for DriverStateService service.
// All implementations must embed UnimplementedDriverStateServiceServer
// for forward compatibility
type DriverStateServiceServer interface {
	GetCandidates(context.Context, *GetCandidatesRequest) (*GetCandidatesResponse, error)
	UpdateLocation(context.Context, *UpdateLocationRequest) (*UpdateLocationResponse, error)
	BatchGetCandidates(context.Context, *BatchGetCandidatesRequest) (*BatchGetCandidatesResponse, error)
	mustEmbedUnimplementedDriverStateServiceServer()
}

// UnimplementedDriverStateServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDriverStateServiceServer struct {
}

func (UnimplementedDriverStateServiceServer) GetCandidates(context.Context, *GetCandidatesRequest) (*GetCandidatesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCandidates not implemented")
}
func (UnimplementedDriverStateServiceServer) UpdateLocation(context.Context, *UpdateLocationRequest) (*UpdateLocationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateLocation not implemented")
}
func (UnimplementedDriverStateServiceServer) BatchGetCandidates(context.Context, *BatchGetCandidatesRequest) (*BatchGetCandidatesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchGetCandidates not implemented")
}
func (UnimplementedDriverStateServiceServer) mustEmbedUnimplementedDriverStateServiceServer() {}

// UnsafeDriverStateServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DriverStateServiceServer will
// result in compilation errors.
type UnsafeDriverStateServiceServer interface {
	mustEmbedUnimplementedDriverStateServiceServer()
}

func RegisterDriverStateServiceServer(s grpc.ServiceRegistrar, srv DriverStateServiceServer) {
	s.RegisterService(&DriverStateService_ServiceDesc, srv)
}

func _DriverStateService_GetCandidates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCandidatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverStateServiceServer).GetCandidates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverStateService_GetCandidates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverStateServiceServer).GetCandidates(ctx, req.(*GetCandidatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverStateService_UpdateLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateLocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverStateServiceServer).UpdateLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverStateService_UpdateLocation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverStateServiceServer).UpdateLocation(ctx, req.(*UpdateLocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverStateService_BatchGetCandidates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchGetCandidatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverStateServiceServer).BatchGetCandidates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverStateService_BatchGetCandidates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverStateServiceServer).BatchGetCandidates(ctx, req.(*BatchGetCandidatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DriverStateService_ServiceDesc is the grpc.ServiceDesc for DriverStateService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DriverStateService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "routematch.shared.proto.v1.DriverStateService",
	HandlerType: (*DriverStateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCandidates",
			Handler:    _DriverStateService_GetCandidates_Handler,
		},
		{
			MethodName: "UpdateLocation",
			Handler:    _DriverStateService_UpdateLocation_Handler,
		},
		{
			MethodName: "BatchGetCandidates",
			Handler:    _DriverStateService_BatchGetCandidates_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "driver_state_service.proto",
}
