global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'order-gateway'
    static_configs:
      - targets: ['order-gateway:8080']

  - job_name: 'ml-batch'
    static_configs:
      - targets: ['ml-batch:8080']

  - job_name: 'dispatch-engine'
    static_configs:
      - targets: ['dispatch-engine:9091']

  - job_name: 'driver-state'
    static_configs:
      - targets: ['driver-state:9092']
